// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttzkathqudeyploezlri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0emthdGhxdWRleXBsb2V6bHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTUzNzMsImV4cCI6MjA3MjYzMTM3M30.lAqDZzy5y5j8Iy5W9prlunIATtGKHkNWJUHkmO4OH7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});